/* Fixture for the independent line-mapping oracle (test_line_oracle.py).
 *
 * The point of this file is that the CORRECT ANSWER IS WRITTEN IN IT. Each
 * marker comment below names a line whose number the test reads out of this
 * source, then asserts the profiler independently arrives at the same number.
 *
 * That indirection is the whole exercise. Every other fixture in the suite was
 * captured by running the tool, so when line-level annotation silently
 * regressed to reporting each function's declaration line, the fixtures
 * encoded the broken behaviour and 165 tests agreed with it. A fixture cannot
 * catch a bug it was generated by. This one is written by hand.
 *
 * Keep the markers on the exact lines they describe, and do not reformat this
 * file without re-checking them.
 */

#include <stdlib.h>

volatile long g_sink;

/* Deliberately not static and not inlinable: the test needs to find these by
 * symbol name, and needs the hot line to be inside the function body rather
 * than folded into a caller. */

__attribute__((noinline))
long oracle_hot_loop(long n)                         /* MARKER: decl_line */
{
    long acc = 0;
    for (long i = 0; i < n; i++) {
        acc += (i * 7919) ^ (acc >> 3);              /* MARKER: hot_line */
    }
    return acc;
}

__attribute__((noinline))
long oracle_second_function(long n)                  /* MARKER: second_decl */
{
    long acc = 1;
    for (long i = 1; i < n; i++) {
        acc = (acc * 31 + i) & 0xffffff;             /* MARKER: second_hot */
    }
    return acc;
}

int main(int argc, char **argv)
{
    long n = argc > 1 ? atol(argv[1]) : 2000000;
    g_sink = oracle_hot_loop(n) + oracle_second_function(n);
    return 0;
}
