/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Agent Command
         * @description Relay a command to the managed agent.
         */
        post: operations["api_agent_command_api_agent_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Browse
         * @description Browse the server filesystem for the wizard's binary/source pickers.
         *     Confined to config.browse_root.
         */
        get: operations["api_browse_api_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/binary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config Route */
        post: operations["config_route_api_config_binary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/pathmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config Route */
        post: operations["config_route_api_config_pathmap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config Route */
        post: operations["config_route_api_config_source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/toolchain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config Route */
        post: operations["config_route_api_config_toolchain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Connect
         * @description Connect to a listen-mode agent.
         */
        post: operations["api_connect_api_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/flamegraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Export Flamegraph
         * @description Export flamegraph as standalone SVG. Uses session data if provided.
         */
        get: operations["api_export_flamegraph_api_export_flamegraph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Export Session
         * @description Export session in collapsed or JSON format.
         */
        get: operations["api_export_session_api_export_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Import
         * @description Import an uploaded perf.data file.
         */
        post: operations["api_import_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Index Files */
        get: operations["api_index_files_api_index_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Index Status */
        get: operations["api_index_status_api_index_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Metrics Current */
        get: operations["api_metrics_current_api_metrics_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Metrics History */
        get: operations["api_metrics_history_api_metrics_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/per-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Per Event
         * @description Pull the cached per-event snapshot (one event, or all). Pairs with
         *     the 'data_version' SSE notify: browsers fetch only the event they're
         *     viewing.
         */
        get: operations["api_per_event_api_per_event_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Sessions List */
        get: operations["api_sessions_list_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Session Replay
         * @description Rebuild session data on the fly from raw chunks (cached on disk —
         *     sessions are immutable once saved).
         */
        get: operations["api_session_replay_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Source
         * @description Return annotated source for a specific file. Optional tid filter.
         */
        get: operations["api_source_api_source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Status */
        get: operations["api_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Stop
         * @description Close the agent connection, triggering normal disconnect flow.
         */
        get: operations["api_stop_api_stop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Stream
         * @description Server-Sent Events endpoint for real-time updates.
         */
        get: operations["api_stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thread-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Thread Summary
         * @description Overview of all threads with CPU breakdown.
         */
        get: operations["api_thread_summary_api_thread_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thread-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Thread View
         * @description Per-thread flamegraph + summary + source_files.
         */
        get: operations["api_thread_view_api_thread_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Time Window
         * @description Flamegraph + function summary restricted to samples received inside
         *     [start, end] (unix seconds). Backs the UI's timeline scrubbing: samples
         *     are stamped with arrival time, so a window on the Device Health
         *     timeline maps to the profile chunks collected in that window. Bounded
         *     by the raw-sample ring buffer (--max-samples).
         */
        get: operations["api_time_window_api_time_window_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Wizard State */
        get: operations["api_wizard_state_api_wizard_state_get"];
        put?: never;
        /** Api Wizard State Update */
        post: operations["api_wizard_state_update_api_wizard_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ui Missing */
        get: operations["ui_missing__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentCommand
         * @description One flag-2 command frame: {id, cmd, args}. The documented command
         *     set of the frozen agent; used for OpenAPI/TS documentation now and
         *     server-side enforcement in API v2.
         */
        AgentCommand: {
            /** Args */
            args?: components["schemas"]["StartArgs"] | components["schemas"]["ConfigureArgs"] | components["schemas"]["ConfigureMetricsArgs"] | {
                [key: string]: unknown;
            };
            /**
             * Cmd
             * @enum {string}
             */
            cmd: "ping" | "status" | "start" | "stop" | "pause" | "resume" | "configure" | "configure_metrics" | "list_processes" | "reprobe" | "probe_binary";
            /** Id */
            id: string;
        };
        /**
         * AgentCommandRequest
         * @description Generic command relay body for POST /api/agent/command.
         */
        AgentCommandRequest: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Cmd
             * @default
             */
            cmd: string;
            /**
             * Timeout
             * @default 60
             */
            timeout: number;
        };
        /** AgentCommandResponse */
        AgentCommandResponse: {
            /** Error */
            error?: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * AgentHello
         * @description The agent's flag-3 hello payload (frozen wire JSON).
         */
        AgentHello: {
            /** Platform */
            platform?: {
                [key: string]: unknown;
            };
            /**
             * Token
             * @default null
             */
            token: string | null;
            /**
             * Type
             * @default hello
             * @constant
             */
            type: "hello";
            /**
             * Version
             * @default
             */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /** BrowseEntry */
        BrowseEntry: {
            /** Is Dir */
            is_dir: boolean;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size */
            size?: number | null;
        };
        /** BrowseResponse */
        BrowseResponse: {
            /** Entries */
            entries: components["schemas"]["BrowseEntry"][];
            /** Parent */
            parent: string;
            /** Path */
            path: string;
        };
        /** ConfigResult */
        ConfigResult: {
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * ConfigureArgs
         * @description configure: change sampling parameters mid-session.
         */
        ConfigureArgs: {
            /**
             * Duration
             * @default null
             */
            duration: number | null;
            /**
             * Frequency
             * @default null
             */
            frequency: number | null;
        };
        /**
         * ConfigureMetricsArgs
         * @description configure_metrics: toggle opt-in collectors / interval on the agent.
         */
        ConfigureMetricsArgs: {
            /**
             * Disk
             * @default null
             */
            disk: boolean | null;
            /**
             * Enabled
             * @default null
             */
            enabled: boolean | null;
            /**
             * Interval
             * @default null
             */
            interval: number | null;
            /**
             * Network
             * @default null
             */
            network: boolean | null;
            /**
             * Threads
             * @default null
             */
            threads: boolean | null;
        };
        /** ConnectRequest */
        ConnectRequest: {
            /** Host */
            host: string;
            /**
             * Port
             * @default 9999
             */
            port: number;
        };
        /** ConnectResponse */
        ConnectResponse: {
            /** Addr */
            addr?: string | null;
            /** Error */
            error?: string | null;
            hello?: components["schemas"]["AgentHello"] | null;
            /** Ok */
            ok: boolean;
        };
        /**
         * DataVersion
         * @description Version stamp for the notify-and-fetch cycle. Broadcast over SSE
         *     (with event_types) and echoed by /api/per-event (without).
         */
        DataVersion: {
            /** Chunk Count */
            chunk_count: number;
            /**
             * Event Types
             * @default null
             */
            event_types: string[] | null;
            /** Total Samples */
            total_samples: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            error: string;
        };
        /** FlamegraphNode */
        FlamegraphNode: {
            /** Children */
            children?: components["schemas"]["FlamegraphNode"][];
            /** Inlined */
            inlined?: boolean | null;
            /** Module */
            module?: string | null;
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** FunctionEntry */
        FunctionEntry: {
            /** Module */
            module: string;
            /** Name */
            name: string;
            /** Percent */
            percent: number;
            /** Samples */
            samples: number;
            /** Self Percent */
            self_percent: number;
            /** Self Samples */
            self_samples: number;
            /** Total Percent */
            total_percent: number;
            /** Total Samples */
            total_samples: number;
        };
        /** FunctionSummary */
        FunctionSummary: {
            /** Functions */
            functions: components["schemas"]["FunctionEntry"][];
            /** Total Samples */
            total_samples: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResponse */
        ImportResponse: {
            /** Event Types */
            event_types: string[];
            /** Session Id */
            session_id: string;
            /** Total Samples */
            total_samples: number;
        };
        /** IndexFilesResponse */
        IndexFilesResponse: {
            /** Files */
            files: string[];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** IndexStatus */
        IndexStatus: {
            /**
             * Indexing
             * @default false
             */
            indexing: boolean;
            /**
             * Source Files Found
             * @default 0
             */
            source_files_found: number;
            /**
             * Symbols Loaded
             * @default 0
             */
            symbols_loaded: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * MetricsFrame
         * @description One health-metrics snapshot from the agent (flag-4 frame). The
         *     agent's shape varies by type and platform — modeled loosely on
         *     purpose; `type` is system|process|network|disk|threads.
         */
        MetricsFrame: {
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /**
             * Type
             * @default
             */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** PathConfigRequest */
        PathConfigRequest: {
            /**
             * Path
             * @default
             */
            path: string;
        };
        /** PathMapConfigRequest */
        PathMapConfigRequest: {
            /** Path Map */
            path_map?: {
                [key: string]: string;
            };
        };
        /** PerEventEntry */
        PerEventEntry: {
            flamegraph: components["schemas"]["FlamegraphNode"];
            function_summary: components["schemas"]["FunctionSummary"];
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Source Files */
            source_files: components["schemas"]["SourceFileRef"][];
            /** Threads */
            threads: components["schemas"]["ThreadRef"][];
        };
        /**
         * PerEventResponse
         * @description GET /api/per-event?event=<evt>
         */
        PerEventResponse: {
            data: components["schemas"]["PerEventEntry"];
            /** Event */
            event: string;
            version: components["schemas"]["DataVersion"];
        };
        /**
         * SSEAgentConnectedEvent
         * @description `agent_connected` event: fired once per new agent session.
         */
        SSEAgentConnectedEvent: {
            /** Agent */
            agent: string;
            /** Platform */
            platform?: {
                [key: string]: unknown;
            };
        };
        /**
         * SSECatalog
         * @description Not an endpoint — enumerates every event on GET /api/stream so the
         *     payload models land in the OpenAPI components for TS generation.
         *
         *     Events: `status` (SSEStatusEvent), `agent_connected`
         *     (SSEAgentConnectedEvent), `event_types` (list[str]), `data_version`
         *     (DataVersion, with event_types), `perf_stat` (dict), `metrics_system`
         *     / `metrics_process` / `metrics_network` / `metrics_disk` /
         *     `metrics_threads` (MetricsFrame).
         */
        SSECatalog: {
            agent_connected: components["schemas"]["SSEAgentConnectedEvent"];
            data_version: components["schemas"]["DataVersion"];
            /** Event Types */
            event_types: string[];
            metrics: components["schemas"]["MetricsFrame"];
            /** Perf Stat */
            perf_stat: {
                [key: string]: unknown;
            };
            status: components["schemas"]["SSEStatusEvent"];
        };
        /**
         * SSEStatusEvent
         * @description `status` event: agent connect/disconnect.
         */
        SSEStatusEvent: {
            /**
             * Agent
             * @default null
             */
            agent: string | null;
            /** Connected */
            connected: boolean;
        };
        /** SessionMetadata */
        SessionMetadata: {
            /**
             * Agent
             * @default
             */
            agent: string;
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
            /** Event Types */
            event_types?: string[];
            /** Metrics Summary */
            metrics_summary?: {
                [key: string]: unknown;
            } | null;
            /** Perf Stat */
            perf_stat?: {
                [key: string]: unknown;
            };
            /** Platform */
            platform?: {
                [key: string]: unknown;
            } | null;
            /** Session Id */
            session_id: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /**
             * Total Samples
             * @default 0
             */
            total_samples: number;
            /**
             * Version
             * @default
             */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /** SessionReplayResponse */
        SessionReplayResponse: {
            metadata: components["schemas"]["SessionMetadata"];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            /** Per Event */
            per_event: {
                [key: string]: components["schemas"]["PerEventEntry"];
            };
        };
        /** SourceFileRef */
        SourceFileRef: {
            /** Found */
            found: boolean;
            /** Functions */
            functions: string[];
            /** Path */
            path: string;
            /** Total Samples */
            total_samples: number;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Error */
            error?: string | null;
            /** File */
            file: string;
            /** Lines */
            lines: {
                [key: string]: unknown;
            }[];
        };
        /**
         * StartArgs
         * @description start: begin collection on a PID. `events` may narrow the probed
         *     record-event set; frequency/duration override the agent defaults.
         */
        StartArgs: {
            /**
             * Duration
             * @default null
             */
            duration: number | null;
            /**
             * Events
             * @default null
             */
            events: string[] | null;
            /**
             * Frequency
             * @default null
             */
            frequency: number | null;
            /** Pid */
            pid: number;
        };
        /** Status */
        Status: {
            /** Agent Addr */
            agent_addr?: string | null;
            /** Agent Connected */
            agent_connected: boolean;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Total Samples */
            total_samples: number;
        };
        /** StopResponse */
        StopResponse: {
            /** Reason */
            reason?: string | null;
            /** Stopped */
            stopped: boolean;
        };
        /** ThreadRef */
        ThreadRef: {
            /** Comm */
            comm: string;
            /** Tid */
            tid: number;
        };
        /** ThreadSummaryEntry */
        ThreadSummaryEntry: {
            /** Comm */
            comm: string;
            /** Percent */
            percent: number;
            /** Samples */
            samples: number;
            /** Tid */
            tid: number;
            /** Top Function */
            top_function: string;
            /** Top Function Samples */
            top_function_samples: number;
            /** Top Functions */
            top_functions: components["schemas"]["ThreadTopFunction"][];
        };
        /** ThreadSummaryResponse */
        ThreadSummaryResponse: {
            /** Threads */
            threads: components["schemas"]["ThreadSummaryEntry"][];
            /** Total Samples */
            total_samples: number;
        };
        /** ThreadTopFunction */
        ThreadTopFunction: {
            /** Name */
            name: string;
            /** Percent */
            percent: number;
            /** Samples */
            samples: number;
        };
        /** ThreadViewResponse */
        ThreadViewResponse: {
            flamegraph: components["schemas"]["FlamegraphNode"];
            function_summary: components["schemas"]["FunctionSummary"];
            /** Source Files */
            source_files?: components["schemas"]["SourceFileRef"][];
        };
        /** TimeWindow */
        TimeWindow: {
            /** End */
            end: number;
            /** Samples */
            samples: number;
            /** Start */
            start: number;
        };
        /** TimeWindowResponse */
        TimeWindowResponse: {
            flamegraph: components["schemas"]["FlamegraphNode"];
            function_summary: components["schemas"]["FunctionSummary"];
            window: components["schemas"]["TimeWindow"];
        };
        /** ToolchainConfigRequest */
        ToolchainConfigRequest: {
            /**
             * Prefix
             * @default
             */
            prefix: string;
            /** Sysroot */
            sysroot?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WizardState */
        WizardState: {
            /**
             * Agent Host
             * @default
             */
            agent_host: string;
            /**
             * Agent Port
             * @default 9999
             */
            agent_port: number;
            /**
             * Binary Path
             * @default
             */
            binary_path: string;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /**
             * Duration
             * @default 8
             */
            duration: number;
            /**
             * Frequency
             * @default 99
             */
            frequency: number;
            /**
             * Perf Verified
             * @default false
             */
            perf_verified: boolean;
            /** Pid */
            pid?: number | null;
            /**
             * Process Name
             * @default
             */
            process_name: string;
            /**
             * Source Dir
             * @default
             */
            source_dir: string;
            /**
             * Step
             * @default 0
             */
            step: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_agent_command_api_agent_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_browse_api_browse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResponse"];
                };
            };
        };
    };
    config_route_api_config_binary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_route_api_config_pathmap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathMapConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_route_api_config_source_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_route_api_config_toolchain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolchainConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_connect_api_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_export_flamegraph_api_export_flamegraph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_export_session_api_export_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_import_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
        };
    };
    api_index_files_api_index_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexFilesResponse"];
                };
            };
        };
    };
    api_index_status_api_index_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
        };
    };
    api_metrics_current_api_metrics_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["MetricsFrame"];
                    };
                };
            };
        };
    };
    api_metrics_history_api_metrics_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsFrame"][];
                };
            };
        };
    };
    api_per_event_api_per_event_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerEventResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_sessions_list_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMetadata"][];
                };
            };
        };
    };
    api_session_replay_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionReplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_source_api_source_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    api_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    api_stop_api_stop_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopResponse"];
                };
            };
        };
    };
    api_stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_thread_summary_api_thread_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadSummaryResponse"];
                };
            };
        };
    };
    api_thread_view_api_thread_view_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadViewResponse"];
                };
            };
        };
    };
    api_time_window_api_time_window_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeWindowResponse"];
                };
            };
        };
    };
    api_wizard_state_api_wizard_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
        };
    };
    api_wizard_state_update_api_wizard_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ui_missing__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
