/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Agent Info
         * @description Current agent connection: address + hello (platform, version).
         */
        get: operations["api_agent_info_api_agent_get"];
        put?: never;
        post?: never;
        /**
         * Api Agent Disconnect
         * @description Close the agent connection, triggering normal disconnect flow.
         */
        delete: operations["api_agent_disconnect_api_agent_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Agent Command
         * @description Relay a command to the managed agent.
         */
        post: operations["api_agent_command_api_agent_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Agent Connect
         * @description Connect to a listen-mode agent.
         */
        post: operations["api_agent_connect_api_agent_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Browse
         * @description Browse the server filesystem for the wizard's binary/source pickers.
         *     Confined to config.browse_root.
         */
        get: operations["api_browse_api_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Config Get */
        get: operations["api_config_get_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Api Config Patch
         * @description Update binary / source dir / path map / toolchain / sysroot in one
         *     request; the source mapper rebuilds once.
         */
        patch: operations["api_config_patch_api_config_patch"];
        trace?: never;
    };
    "/api/index/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Index Files */
        get: operations["api_index_files_api_index_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Index Status */
        get: operations["api_index_status_api_index_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Live Export
         * @description Export the live in-memory profile (bounded by --max-samples).
         */
        get: operations["api_live_export_api_live_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Metrics Current */
        get: operations["api_metrics_current_api_metrics_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Metrics History */
        get: operations["api_metrics_history_api_metrics_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Sessions List */
        get: operations["api_sessions_list_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Sessions Import
         * @description Import an uploaded perf.data file as a saved session.
         */
        post: operations["api_sessions_import_api_sessions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Session Replay
         * @description Rebuild session data on the fly from raw chunks (cached on disk —
         *     sessions are immutable once saved).
         */
        get: operations["api_session_replay_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Api Session Delete */
        delete: operations["api_session_delete_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Session Export
         * @description Export a saved session: collapsed stacks, full JSON, or SVG
         *     flamegraph (per event).
         */
        get: operations["api_session_export_api_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Snapshot
         * @description Pull the cached per-event snapshot (one event, or all). Pairs with
         *     the 'data_version' SSE notify: browsers fetch only the event they're
         *     viewing.
         */
        get: operations["api_snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Source
         * @description Return annotated source for a specific file. Optional tid filter.
         */
        get: operations["api_source_api_source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Status */
        get: operations["api_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Stream
         * @description Server-Sent Events endpoint for real-time updates.
         *
         *     Events: `status`, `agent`, `data_version` (carries event_types),
         *     `perf_stat`, `metrics` (discriminated by its `type` field).
         */
        get: operations["api_stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Threads
         * @description Overview of all threads with CPU breakdown.
         */
        get: operations["api_threads_api_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{tid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Thread View
         * @description Per-thread flamegraph + summary + source_files.
         */
        get: operations["api_thread_view_api_threads__tid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Window
         * @description Flamegraph + function summary restricted to samples received inside
         *     [start, end] (unix seconds). Backs the UI's timeline scrubbing: samples
         *     are stamped with arrival time, so a window on the Device Health
         *     timeline maps to the profile chunks collected in that window. Bounded
         *     by the raw-sample ring buffer (--max-samples).
         */
        get: operations["api_window_api_window_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Wizard Get */
        get: operations["api_wizard_get_api_wizard_get"];
        /** Api Wizard Put */
        put: operations["api_wizard_put_api_wizard_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ui Missing */
        get: operations["ui_missing__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentCommand
         * @description One flag-2 command frame: {id, cmd, args}. The documented command
         *     set of the frozen agent; AgentCommandRequest enforces the same set
         *     server-side.
         */
        AgentCommand: {
            /** Args */
            args?: components["schemas"]["StartArgs"] | components["schemas"]["ConfigureArgs"] | components["schemas"]["ConfigureMetricsArgs"] | {
                [key: string]: unknown;
            };
            /**
             * Cmd
             * @enum {string}
             */
            cmd: "ping" | "status" | "list_processes" | "verify_pid" | "verify_perf" | "reprobe" | "start" | "stop" | "pause" | "resume" | "configure" | "configure_metrics" | "update";
            /** Id */
            id: string;
        };
        /**
         * AgentCommandRequest
         * @description Command relay body for POST /api/agent/command. `cmd` is enforced
         *     against the frozen agent's command set.
         */
        AgentCommandRequest: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Cmd
             * @enum {string}
             */
            cmd: "ping" | "status" | "list_processes" | "verify_pid" | "verify_perf" | "reprobe" | "start" | "stop" | "pause" | "resume" | "configure" | "configure_metrics" | "update";
            /**
             * Timeout
             * @default 60
             */
            timeout: number;
        };
        /** AgentCommandResponse */
        AgentCommandResponse: {
            /** Error */
            error?: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * AgentHello
         * @description The agent's flag-3 hello payload (frozen wire JSON).
         */
        AgentHello: {
            /** Platform */
            platform?: {
                [key: string]: unknown;
            };
            /**
             * Token
             * @default null
             */
            token: string | null;
            /**
             * Type
             * @default hello
             * @constant
             */
            type: "hello";
            /**
             * Version
             * @default
             */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * AgentInfo
         * @description GET /api/agent — current agent connection.
         */
        AgentInfo: {
            /** Addr */
            addr?: string | null;
            /** Connected */
            connected: boolean;
            hello?: components["schemas"]["AgentHello"] | null;
        };
        /** BrowseEntry */
        BrowseEntry: {
            /** Is Dir */
            is_dir: boolean;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size */
            size?: number | null;
        };
        /** BrowseResponse */
        BrowseResponse: {
            /** Entries */
            entries: components["schemas"]["BrowseEntry"][];
            /** Parent */
            parent: string;
            /** Path */
            path: string;
        };
        /**
         * ConfigState
         * @description GET /api/config — the resolvable-path parts of the server config.
         *     Also the PATCH response (the state after the update).
         */
        ConfigState: {
            /** Addr2Line */
            addr2line?: string | null;
            /** Binary */
            binary?: string | null;
            /**
             * Inline
             * @default true
             */
            inline: boolean;
            /** Path Map */
            path_map?: {
                [key: string]: string;
            } | null;
            /** Readelf */
            readelf?: string | null;
            /** Source Dir */
            source_dir: string;
            /** Sysroot */
            sysroot?: string | null;
        };
        /**
         * ConfigUpdate
         * @description PATCH /api/config — every field optional; only provided fields
         *     change. `binary: ""` clears the binary; `sysroot: ""` clears the
         *     sysroot; the source mapper rebuilds once per request.
         */
        ConfigUpdate: {
            /** Binary */
            binary?: string | null;
            /** Path Map */
            path_map?: {
                [key: string]: string;
            } | null;
            /** Source Dir */
            source_dir?: string | null;
            /** Sysroot */
            sysroot?: string | null;
            /** Toolchain Prefix */
            toolchain_prefix?: string | null;
        };
        /**
         * ConfigureArgs
         * @description configure: change sampling parameters mid-session.
         */
        ConfigureArgs: {
            /**
             * Duration
             * @default null
             */
            duration: number | null;
            /**
             * Frequency
             * @default null
             */
            frequency: number | null;
        };
        /**
         * ConfigureMetricsArgs
         * @description configure_metrics: toggle opt-in collectors / interval on the agent.
         */
        ConfigureMetricsArgs: {
            /**
             * Disk
             * @default null
             */
            disk: boolean | null;
            /**
             * Enabled
             * @default null
             */
            enabled: boolean | null;
            /**
             * Interval
             * @default null
             */
            interval: number | null;
            /**
             * Network
             * @default null
             */
            network: boolean | null;
            /**
             * Threads
             * @default null
             */
            threads: boolean | null;
        };
        /** ConnectRequest */
        ConnectRequest: {
            /** Host */
            host: string;
            /**
             * Port
             * @default 9999
             */
            port: number;
        };
        /** ConnectResponse */
        ConnectResponse: {
            /** Addr */
            addr?: string | null;
            hello?: components["schemas"]["AgentHello"] | null;
            /** Ok */
            ok: boolean;
        };
        /**
         * DataVersion
         * @description Version stamp for the notify-and-fetch cycle. Broadcast over SSE
         *     (with event_types) and echoed by /api/snapshot (without).
         */
        DataVersion: {
            /** Chunk Count */
            chunk_count: number;
            /**
             * Event Types
             * @default null
             */
            event_types: string[] | null;
            /** Total Samples */
            total_samples: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description Every non-2xx response renders as this envelope.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FlamegraphNode */
        FlamegraphNode: {
            /** Children */
            children?: components["schemas"]["FlamegraphNode"][];
            /** Inlined */
            inlined?: boolean | null;
            /** Module */
            module?: string | null;
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** FunctionEntry */
        FunctionEntry: {
            /** Module */
            module: string;
            /** Name */
            name: string;
            /** Percent */
            percent: number;
            /** Samples */
            samples: number;
            /** Self Percent */
            self_percent: number;
            /** Self Samples */
            self_samples: number;
            /** Total Percent */
            total_percent: number;
            /** Total Samples */
            total_samples: number;
        };
        /** FunctionSummary */
        FunctionSummary: {
            /** Functions */
            functions: components["schemas"]["FunctionEntry"][];
            /** Total Samples */
            total_samples: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResponse */
        ImportResponse: {
            /** Event Types */
            event_types: string[];
            /** Session Id */
            session_id: string;
            /** Total Samples */
            total_samples: number;
        };
        /** IndexFilesResponse */
        IndexFilesResponse: {
            /** Files */
            files: string[];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** IndexStatus */
        IndexStatus: {
            /**
             * Indexing
             * @default false
             */
            indexing: boolean;
            /**
             * Source Files Found
             * @default 0
             */
            source_files_found: number;
            /**
             * Symbols Loaded
             * @default 0
             */
            symbols_loaded: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * MetricsFrame
         * @description One health-metrics snapshot from the agent (flag-4 frame). The
         *     agent's shape varies by type and platform — modeled loosely on
         *     purpose; `type` is system|process|network|disk|threads.
         */
        MetricsFrame: {
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /**
             * Type
             * @default
             */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** PerEventEntry */
        PerEventEntry: {
            flamegraph: components["schemas"]["FlamegraphNode"];
            function_summary: components["schemas"]["FunctionSummary"];
            /** Source */
            source?: {
                [key: string]: unknown;
            } | null;
            /** Source Files */
            source_files: components["schemas"]["SourceFileRef"][];
            /** Threads */
            threads: components["schemas"]["ThreadRef"][];
        };
        /**
         * SSEAgentEvent
         * @description `agent` event: fired once per new agent session.
         */
        SSEAgentEvent: {
            /** Agent */
            agent: string;
            /** Platform */
            platform?: {
                [key: string]: unknown;
            };
        };
        /**
         * SSECatalog
         * @description Not an endpoint — enumerates every event on GET /api/stream so the
         *     payload models land in the OpenAPI components for TS generation.
         *
         *     Events: `status` (SSEStatusEvent), `agent` (SSEAgentEvent),
         *     `data_version` (DataVersion, with event_types), `perf_stat` (dict),
         *     `metrics` (MetricsFrame, discriminated by its `type` field).
         */
        SSECatalog: {
            agent: components["schemas"]["SSEAgentEvent"];
            data_version: components["schemas"]["DataVersion"];
            metrics: components["schemas"]["MetricsFrame"];
            /** Perf Stat */
            perf_stat: {
                [key: string]: unknown;
            };
            status: components["schemas"]["SSEStatusEvent"];
        };
        /**
         * SSEStatusEvent
         * @description `status` event: agent connect/disconnect.
         */
        SSEStatusEvent: {
            /**
             * Agent
             * @default null
             */
            agent: string | null;
            /** Connected */
            connected: boolean;
        };
        /** SessionDeleteResponse */
        SessionDeleteResponse: {
            /** Ok */
            ok: boolean;
            /** Session Id */
            session_id: string;
        };
        /**
         * SessionListResponse
         * @description GET /api/sessions?offset=&limit=
         */
        SessionListResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Sessions */
            sessions: components["schemas"]["SessionMetadata"][];
            /** Total */
            total: number;
        };
        /** SessionMetadata */
        SessionMetadata: {
            /**
             * Agent
             * @default
             */
            agent: string;
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
            /** Event Types */
            event_types?: string[];
            /** Metrics Summary */
            metrics_summary?: {
                [key: string]: unknown;
            } | null;
            /** Perf Stat */
            perf_stat?: {
                [key: string]: unknown;
            };
            /** Platform */
            platform?: {
                [key: string]: unknown;
            } | null;
            /** Session Id */
            session_id: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /**
             * Total Samples
             * @default 0
             */
            total_samples: number;
            /**
             * Version
             * @default
             */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /** SessionReplayResponse */
        SessionReplayResponse: {
            metadata: components["schemas"]["SessionMetadata"];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            /** Per Event */
            per_event: {
                [key: string]: components["schemas"]["PerEventEntry"];
            };
        };
        /**
         * SnapshotResponse
         * @description GET /api/snapshot?event=<evt>
         */
        SnapshotResponse: {
            data: components["schemas"]["PerEventEntry"];
            /** Event */
            event: string;
            version: components["schemas"]["DataVersion"];
        };
        /** SourceFileRef */
        SourceFileRef: {
            /** Found */
            found: boolean;
            /** Functions */
            functions: string[];
            /** Path */
            path: string;
            /** Total Samples */
            total_samples: number;
        };
        /** SourceResponse */
        SourceResponse: {
            /** File */
            file: string;
            /** Lines */
            lines: {
                [key: string]: unknown;
            }[];
        };
        /**
         * StartArgs
         * @description start: begin collection on a PID. `events` may narrow the probed
         *     record-event set; frequency/duration override the agent defaults.
         */
        StartArgs: {
            /**
             * Duration
             * @default null
             */
            duration: number | null;
            /**
             * Events
             * @default null
             */
            events: string[] | null;
            /**
             * Frequency
             * @default null
             */
            frequency: number | null;
            /** Pid */
            pid: number;
        };
        /** Status */
        Status: {
            /** Agent Addr */
            agent_addr?: string | null;
            /** Agent Connected */
            agent_connected: boolean;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Total Samples */
            total_samples: number;
        };
        /** StopResponse */
        StopResponse: {
            /** Reason */
            reason?: string | null;
            /** Stopped */
            stopped: boolean;
        };
        /** ThreadRef */
        ThreadRef: {
            /** Comm */
            comm: string;
            /** Tid */
            tid: number;
        };
        /** ThreadSummaryEntry */
        ThreadSummaryEntry: {
            /** Comm */
            comm: string;
            /** Percent */
            percent: number;
            /** Samples */
            samples: number;
            /** Tid */
            tid: number;
            /** Top Function */
            top_function: string;
            /** Top Function Samples */
            top_function_samples: number;
            /** Top Functions */
            top_functions: components["schemas"]["ThreadTopFunction"][];
        };
        /** ThreadSummaryResponse */
        ThreadSummaryResponse: {
            /** Threads */
            threads: components["schemas"]["ThreadSummaryEntry"][];
            /** Total Samples */
            total_samples: number;
        };
        /** ThreadTopFunction */
        ThreadTopFunction: {
            /** Name */
            name: string;
            /** Percent */
            percent: number;
            /** Samples */
            samples: number;
        };
        /** ThreadViewResponse */
        ThreadViewResponse: {
            flamegraph: components["schemas"]["FlamegraphNode"];
            function_summary: components["schemas"]["FunctionSummary"];
            /** Source Files */
            source_files?: components["schemas"]["SourceFileRef"][];
        };
        /** TimeWindow */
        TimeWindow: {
            /** End */
            end: number;
            /** Samples */
            samples: number;
            /** Start */
            start: number;
        };
        /** TimeWindowResponse */
        TimeWindowResponse: {
            flamegraph: components["schemas"]["FlamegraphNode"];
            function_summary: components["schemas"]["FunctionSummary"];
            window: components["schemas"]["TimeWindow"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WizardState */
        WizardState: {
            /**
             * Agent Host
             * @default
             */
            agent_host: string;
            /**
             * Agent Port
             * @default 9999
             */
            agent_port: number;
            /**
             * Binary Path
             * @default
             */
            binary_path: string;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /**
             * Duration
             * @default 8
             */
            duration: number;
            /**
             * Frequency
             * @default 99
             */
            frequency: number;
            /**
             * Perf Verified
             * @default false
             */
            perf_verified: boolean;
            /** Pid */
            pid?: number | null;
            /**
             * Process Name
             * @default
             */
            process_name: string;
            /**
             * Source Dir
             * @default
             */
            source_dir: string;
            /**
             * Step
             * @default 0
             */
            step: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_agent_info_api_agent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInfo"];
                };
            };
        };
    };
    api_agent_disconnect_api_agent_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopResponse"];
                };
            };
        };
    };
    api_agent_command_api_agent_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCommandResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_agent_connect_api_agent_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_browse_api_browse_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_config_get_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigState"];
                };
            };
        };
    };
    api_config_patch_api_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigState"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_index_files_api_index_files_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexFilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_index_status_api_index_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
        };
    };
    api_live_export_api_live_export_get: {
        parameters: {
            query?: {
                format?: string;
                event?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_metrics_current_api_metrics_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["MetricsFrame"];
                    };
                };
            };
        };
    };
    api_metrics_history_api_metrics_history_get: {
        parameters: {
            query?: {
                type?: string;
                start?: number | null;
                end?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsFrame"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_sessions_list_api_sessions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_sessions_import_api_sessions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_session_replay_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionReplayResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_session_delete_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeleteResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_session_export_api_sessions__session_id__export_get: {
        parameters: {
            query?: {
                format?: string;
                event?: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_snapshot_api_snapshot_get: {
        parameters: {
            query?: {
                event?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_source_api_source_get: {
        parameters: {
            query: {
                file: string;
                event?: string | null;
                tid?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    api_stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_threads_api_threads_get: {
        parameters: {
            query?: {
                event?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_thread_view_api_threads__tid__get: {
        parameters: {
            query?: {
                event?: string;
            };
            header?: never;
            path: {
                tid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_window_api_window_get: {
        parameters: {
            query: {
                start: number;
                end: number;
                event?: string;
                tid?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeWindowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_wizard_get_api_wizard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
        };
    };
    api_wizard_put_api_wizard_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ui_missing__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
