#!/usr/bin/env python3
"""Assert every place that records the PerfLens version agrees with VERSION.

The repo-root ``VERSION`` file is the single source of truth. The agent bakes
it in at compile time (agent-c/Makefile), the release workflow reads it for
asset names, and the frontend injects it at build time (vite.config.ts).

This exists because a hand-typed ``v0.8.0`` sat in the docs drawer of a UI
that shipped as 0.7.0 -- invisible to every test, and absent from the release
checklist. Wire it into CI so the checklist can't be forgotten again.

Usage:  python tools/check_version.py [--quiet]
Exit:   0 when everything agrees, 1 otherwise (mismatches printed to stderr).
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# A literal version in shipped UI source is exactly the drift this guards
# against -- it must come from __PERFLENS_VERSION__ instead.
LITERAL_VERSION = re.compile(r'\bv\d+\.\d+\.\d+\b')


def _read(*parts):
    with open(os.path.join(ROOT, *parts), encoding='utf-8') as f:
        return f.read()


def _search(pattern, text, where):
    m = re.search(pattern, text, re.M)
    if not m:
        raise SystemExit(f'check_version: no version found in {where}')
    return m.group(1)


def collect():
    """Return {label: version} for every file that records the version."""
    found = {'VERSION': _read('VERSION').strip()}
    found['pyproject.toml'] = _search(
        r'^version\s*=\s*[\'"]([^\'"]+)[\'"]', _read('pyproject.toml'), 'pyproject.toml')
    found['src/perflens/__init__.py'] = _search(
        r'^__version__\s*=\s*[\'"]([^\'"]+)[\'"]',
        _read('src', 'perflens', '__init__.py'), 'src/perflens/__init__.py')
    found['frontend/package.json'] = json.loads(
        _read('frontend', 'package.json'))['version']

    # Generated by tools/export_openapi.py; CI diff-checks it separately, but a
    # stale regeneration shows up here first and with a clearer message.
    found['frontend/openapi.json'] = json.loads(
        _read('frontend', 'openapi.json'))['info']['version']

    lock = json.loads(_read('frontend', 'package-lock.json'))
    found['frontend/package-lock.json'] = lock['version']
    root_pkg = lock.get('packages', {}).get('')
    if root_pkg and 'version' in root_pkg:
        found['frontend/package-lock.json (packages."")'] = root_pkg['version']
    return found


def hardcoded_ui_versions():
    """Version literals left in frontend source, which must be injected."""
    src = os.path.join(ROOT, 'frontend', 'src')
    hits = []
    for dirpath, _dirnames, filenames in os.walk(src):
        for name in filenames:
            if not name.endswith(('.ts', '.tsx')):
                continue
            path = os.path.join(dirpath, name)
            # The test asserts on the injected value; it names no literal.
            if os.path.basename(path) == 'version.test.ts':
                continue
            with open(path, encoding='utf-8') as f:
                for lineno, line in enumerate(f, 1):
                    if LITERAL_VERSION.search(line):
                        rel = os.path.relpath(path, ROOT)
                        hits.append(f'{rel}:{lineno}: {line.strip()}')
    return hits


def main():
    quiet = '--quiet' in sys.argv
    found = collect()
    canonical = found['VERSION']

    problems = [f'{label} = {value!r} (VERSION = {canonical!r})'
                for label, value in found.items() if value != canonical]
    problems += [f'hardcoded version literal: {h}' for h in hardcoded_ui_versions()]

    if problems:
        print('check_version: FAIL', file=sys.stderr)
        for p in problems:
            print(f'  - {p}', file=sys.stderr)
        return 1

    if not quiet:
        print(f'check_version: OK -- all {len(found)} locations agree on {canonical}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
